!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE MOD_VARIANCE_B
  USE MOD_MEAN, ONLY : mean
  USE MOD_MEAN_B, ONLY : mean_b
  USE MOD_MATH, ONLY : subtract
  USE MOD_MATH_B, ONLY : divide_b, subtract_b
  IMPLICIT NONE
  PUBLIC :: variance_b
  PRIVATE 

CONTAINS
!  Differentiation of variance in reverse (adjoint) mode (with options i4 dr8 r8):
!   gradient     of useful results: b
!   with respect to varying inputs: a b
!   RW status of diff variables: a:out b:in-zero
  SUBROUTINE VARIANCE_B(a, ad, b, bd)
    IMPLICIT NONE
    real(8), DIMENSION(:), INTENT(INOUT) :: a
    real(8), DIMENSION(:), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: bd
    real(8) :: meanval
    real(8) :: meanvald
    real(8) :: temp1
    real(8) :: temp1d
    real(8) :: temp2
    real(8) :: temp2d
    real(8) :: n
    INTEGER*8 :: i
    INTRINSIC SIZE
    INTRINSIC REAL
    INTRINSIC INT
    INTEGER*8 :: ad_to
    CALL MEAN(a, meanval)
    n = REAL(SIZE(a), 8)
    DO i=1,INT(n)
      CALL PUSHREAL8(temp1)
      CALL SUBTRACT(a(i), meanval, temp1)
    END DO
    ad_to = i - 1
    ad = 0.0_8
    meanvald = 0.0_8
    DO i=ad_to,1,-1
      temp2d = bd
      CALL DIVIDE_B(temp1, temp1d, n, temp2, temp2d)
      temp1d = 2*temp1*temp1d
      CALL POPREAL8(temp1)
      CALL SUBTRACT_B(a(i), ad(i), meanval, meanvald, temp1, temp1d)
    END DO
    CALL MEAN_B(a, ad, meanval, meanvald)
    bd = 0.0_8
  END SUBROUTINE VARIANCE_B

END MODULE MOD_VARIANCE_B
