!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE MOD_MATH_B
  IMPLICIT NONE
  PUBLIC :: divide_b, add_b, subtract_b
  PRIVATE 

CONTAINS
!  Differentiation of divide in reverse (adjoint) mode (with options i4 dr8 r8):
!   gradient     of useful results: c
!   with respect to varying inputs: a
  SUBROUTINE DIVIDE_B(a, ad, b, c, cd)
    IMPLICIT NONE
    real(8), INTENT(INOUT) :: a
    real(8), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: c
    real(8), INTENT(INOUT) :: cd
    ad = cd/b
  END SUBROUTINE DIVIDE_B

!  Differentiation of add in reverse (adjoint) mode (with options i4 dr8 r8):
!   gradient     of useful results: b c
!   with respect to varying inputs: a b
  SUBROUTINE ADD_B(a, ad, b, bd, c, cd)
    IMPLICIT NONE
    real(8), INTENT(INOUT) :: a
    real(8), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: bd
    real(8), INTENT(INOUT) :: c
    real(8), INTENT(INOUT) :: cd
    ad = cd
    bd = bd + cd
  END SUBROUTINE ADD_B

!  Differentiation of subtract in reverse (adjoint) mode (with options i4 dr8 r8):
!   gradient     of useful results: a b c
!   with respect to varying inputs: a b
  SUBROUTINE SUBTRACT_B(a, ad, b, bd, c, cd)
    IMPLICIT NONE
    real(8), INTENT(INOUT) :: a
    real(8), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: bd
    real(8), INTENT(INOUT) :: c
    real(8), INTENT(INOUT) :: cd
    ad = ad + cd
    bd = bd - cd
  END SUBROUTINE SUBTRACT_B

END MODULE MOD_MATH_B
