!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE MOD_MATH_D
  IMPLICIT NONE
  PUBLIC :: divide_d, add_d, subtract_d
  PRIVATE 

CONTAINS
!  Differentiation of divide in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: c
!   with respect to varying inputs: a
  SUBROUTINE DIVIDE_D(a, ad, b, c, cd)
    IMPLICIT NONE
    real(8), INTENT(INOUT) :: a
    real(8), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: c
    real(8), INTENT(INOUT) :: cd
    cd = ad/b
    c = a/b
  END SUBROUTINE DIVIDE_D

!  Differentiation of add in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: c
!   with respect to varying inputs: a b
  SUBROUTINE ADD_D(a, ad, b, bd, c, cd)
    IMPLICIT NONE
    real(8), INTENT(INOUT) :: a
    real(8), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: bd
    real(8), INTENT(INOUT) :: c
    real(8), INTENT(INOUT) :: cd
    cd = ad + bd
    c = a + b
  END SUBROUTINE ADD_D

!  Differentiation of subtract in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: c
!   with respect to varying inputs: a b
  SUBROUTINE SUBTRACT_D(a, ad, b, bd, c, cd)
    IMPLICIT NONE
    real(8), INTENT(INOUT) :: a
    real(8), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: bd
    real(8), INTENT(INOUT) :: c
    real(8), INTENT(INOUT) :: cd
    cd = ad - bd
    c = a - b
  END SUBROUTINE SUBTRACT_D

END MODULE MOD_MATH_D
