!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (master) -  9 Oct 2020 17:47
!
MODULE MOD_MEAN_D
  USE MOD_MATH_D, ONLY : divide_d, add_d
  IMPLICIT NONE
  PUBLIC :: mean_d
  PRIVATE 

CONTAINS
!  Differentiation of mean in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: b
!   with respect to varying inputs: a
!   RW status of diff variables: a:in b:out
  SUBROUTINE MEAN_D(a, ad, b, bd)
    IMPLICIT NONE
    real(8), DIMENSION(:), INTENT(INOUT) :: a
    real(8), DIMENSION(:), INTENT(INOUT) :: ad
    real(8), INTENT(INOUT) :: b
    real(8), INTENT(INOUT) :: bd
    real(8) :: temp
    real(8) :: tempd
    real(8) :: n
    INTEGER*8 :: i
    INTRINSIC SIZE
    INTRINSIC REAL
    INTRINSIC INT
    n = REAL(SIZE(a), 8)
    b = 0.0
    bd = 0.0_8
    DO i=1,INT(n)
      CALL ADD_D(b, bd, a(i), ad(i), temp, tempd)
      bd = tempd
      b = temp
    END DO
    CALL DIVIDE_D(b, bd, n, temp, tempd)
    bd = tempd
    b = temp
  END SUBROUTINE MEAN_D

END MODULE MOD_MEAN_D
