name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build & Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip3 install -r requirements.txt

    - name: Build
      run: |
        cp config/defaults/config.Ubuntu_GFORTRAN.mk config/config.mk
        make

    - name: Test
      run: |
        cd tests
        testflo -v .
